from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.enum.style import WD_STYLE_TYPE
from pathlib import Path

ROOT=Path(__file__).parent.parent; OUT=ROOT/'docs/AKP_Web_Admin_Developer_Documentation.docx'; IMG=ROOT/'docs/assets/admin-reference-01.png'
BLUE='17365D'; DARK='1F2937'; BORDER='D9D9D9'
def shade(c,fill):
    p=c._tc.get_or_add_tcPr(); s=OxmlElement('w:shd'); s.set(qn('w:fill'),fill); p.append(s)
def setcell(c,text,b=False,color=DARK,size=8.5):
    c.text=''; p=c.paragraphs[0]; p.paragraph_format.space_after=Pt(2); r=p.add_run(str(text)); r.bold=b; r.font.size=Pt(size); r.font.color.rgb=RGBColor.from_string(color)
def tbl(doc,heads,rows):
    t=doc.add_table(rows=1,cols=len(heads)); t.alignment=WD_TABLE_ALIGNMENT.CENTER; t.style='Table Grid'
    for c,h in zip(t.rows[0].cells,heads): shade(c,BLUE); setcell(c,h,True,'FFFFFF',8.5)
    for ri,row in enumerate(rows):
        cs=t.add_row().cells
        for c,v in zip(cs,row):
            if ri%2: shade(c,'F7F9FC')
            setcell(c,v)
    doc.add_paragraph(''); return t
def h(doc,text,l=1): return doc.add_heading(text,level=l)
def b(doc,text): doc.add_paragraph(text,style='List Bullet')
def code(doc,text): doc.add_paragraph(text,style='Code Block')
doc=Document(); s=doc.sections[0]; s.top_margin=Inches(.7); s.bottom_margin=Inches(.65); s.left_margin=Inches(.8); s.right_margin=Inches(.8)
doc.styles['Normal'].font.name='Aptos'; doc.styles['Normal'].font.size=Pt(10.5); doc.styles['Normal'].font.color.rgb=RGBColor.from_string(DARK); doc.styles['Normal'].paragraph_format.space_after=Pt(6)
for n,z,col in [('Title',28,BLUE),('Heading 1',18,BLUE),('Heading 2',13,BLUE),('Heading 3',11,DARK)]:
    st=doc.styles[n]; st.font.name='Aptos Display'; st.font.size=Pt(z); st.font.bold=True; st.font.color.rgb=RGBColor.from_string(col)
cs=doc.styles.add_style('Code Block',WD_STYLE_TYPE.PARAGRAPH); cs.font.name='Cascadia Mono'; cs.font.size=Pt(8.5); cs.font.color.rgb=RGBColor.from_string('334155'); cs.paragraph_format.left_indent=Inches(.25)
doc.sections[0].header.paragraphs[0].text='AKP NATIVE PRODUCTS  |  WEB ADMIN DEVELOPER GUIDE'; doc.sections[0].header.paragraphs[0].alignment=WD_ALIGN_PARAGRAPH.RIGHT
f=doc.sections[0].footer.paragraphs[0]; f.alignment=WD_ALIGN_PARAGRAPH.CENTER; f.add_run('Internal working specification  •  '); r=f.add_run(); a=OxmlElement('w:fldChar'); a.set(qn('w:fldCharType'),'begin'); i=OxmlElement('w:instrText'); i.text=' PAGE '; z=OxmlElement('w:fldChar'); z.set(qn('w:fldCharType'),'end'); r._r.extend([a,i,z])
p=doc.add_paragraph(style='Title'); p.alignment=1; p.add_run('AKP Native Products Web Admin')
p=doc.add_paragraph(); p.alignment=1; r=p.add_run('Developer Documentation and Implementation Specification'); r.bold=True; r.font.size=Pt(16); r.font.color.rgb=RGBColor.from_string('475569')
doc.add_paragraph('\n')
p=doc.add_paragraph(); p.alignment=1; p.add_run('For the current Next.js and HeroUI project\nPrepared 09 October 2026\nVersion 1.0 working draft').font.size=Pt(11)
doc.add_paragraph('\n')
p=doc.add_paragraph(); p.alignment=1; p.add_run('Purpose').bold=True
p=doc.add_paragraph('A build guide for the web-based administration system of AKP Native Products Trading. It converts the supplied requirements and interface references into a practical engineering plan, route map, data model, access rules, workflows, and acceptance checklist.'); p.alignment=1
doc.add_page_break()
h(doc,'How to use this document'); doc.add_paragraph('This guide is intended for a project maker, developer, or coding agent. It separates confirmed project facts from proposed implementation decisions. The supplied capstone requirements and screen references define what the admin must do; the repository defines how it should be built today.')
tbl(doc,['Evidence type','How it is used'],[('Project repository','Authoritative for current framework, folder conventions, dependencies, and existing code.'),('Supplied requirements PDFs','Authoritative for business scope, module responsibilities, role expectations, and workflow intent.'),('Supplied admin screen PDF','Visual reference for navigation, labels, tables, cards, status names, and information density.'),('This specification','Implementation-ready interpretation. Proposed items should be confirmed before production.')])
h(doc,'Executive build decision'); doc.add_paragraph('Build the admin as a protected Next.js App Router application using TypeScript, HeroUI, Tailwind CSS, Lucide icons, Prisma 7, and PostgreSQL. Keep server-side reads and mutations close to the feature that owns them. The current repository is a starter template, so business tables, authentication, authorization, audit trail, reporting, and backup flows remain to be implemented.')
h(doc,'Current repository baseline'); tbl(doc,['Area','Current choice','Guidance'],[('Framework','Next.js 16 App Router','Use app/ routes and server components by default.'),('Language','TypeScript 5.6','Use strict types for domain records and payloads.'),('UI','HeroUI 3.2.5 + Tailwind 4','Do not introduce a second design system.'),('Database','PostgreSQL + Prisma 7.10','Replace starter user/contact schema with domain schema.'),('Icons','lucide-react','Use consistently in nav, actions, status, and empty states.'),('Existing nav','components/ui/sidebar.tsx','Expand current items into grouped admin navigation.')])
h(doc,'1 Product vision and admin scope'); doc.add_paragraph('The web admin is the operational control center for product catalog, stock, customers, orders, payments, delivery, returns, feedback, marketing, reports, auditability, and data recovery. It replaces notebooks, receipt books, spreadsheets, social-message coordination, and manual stock checks with one operational source of truth.')
h(doc,'Primary users',2); tbl(doc,['Role','Purpose','Access posture'],[('Owner','Manage the business, users, reports, system controls, backups, and all records.','Full access including restore.'),('Staff','Process catalog, inventory, customers, orders, payments, delivery, returns, feedback, marketing, and reports.','Operational access; limited audit/system controls.'),('Customer and delivery roles','Outside the present web-admin focus; represented as linked records/events.','Do not expose their separate surfaces here yet.')])
h(doc,'Navigation information architecture',2); tbl(doc,['Group','Routes'],[('Overview','/dashboard'),('Operations','/orders, /inventory, /delivery-personnel, /returns-refunds'),('Customers','/customers, /feedback, /payments'),('Catalog and Marketing','/products, /heritage-showcase, /promotions, /notifications'),('System','/reports, /audit-logs, /backup-restore, /users, /settings')])
h(doc,'2 Visual and interaction direction'); doc.add_paragraph('The supplied screen references show a desktop-first shell with persistent left navigation, top utility bar, global search, compact data tables, status badges, export actions, date filters, and dashboard cards. Preserve this information architecture while making it responsive enough for tablet use.')
if IMG.exists():
    p=doc.add_paragraph(); p.alignment=1; p.add_run().add_picture(str(IMG),width=Inches(6.5)); p=doc.add_paragraph('Figure 1. Supplied administration screen reference. Use it as a visual guide, not a pixel-perfect constraint.'); p.alignment=1; p.runs[0].italic=True; p.runs[0].font.size=Pt(8.5)
h(doc,'Shell rules',2)
for x in ['Desktop: persistent sidebar around 240 px; content scrolls independently.','Top bar: product name, global search, notifications, current role, account menu, sign out.','Tables: search/filter row, pagination, loading/empty/error states, confirmation for destructive actions.','Statuses use text plus color; never rely on color alone.','Forms validate on the server, show field-level errors, preserve safe values, and confirm successful mutations.']: b(doc,x)
h(doc,'3 Technical architecture'); doc.add_paragraph('Use a feature-oriented App Router structure. Server components fetch through typed server functions. Route handlers serve client-triggered mutations, exports, webhooks, and files. Authorization lives in a reusable server-only helper; a hidden button is never the security boundary.')
code(doc,'app/(admin)/dashboard/page.tsx\napp/(admin)/orders/page.tsx\napp/(admin)/inventory/page.tsx\napp/(admin)/products/page.tsx\napp/(admin)/customers/page.tsx\napp/(admin)/reports/page.tsx\napp/api/admin/[resource]/route.ts\ncomponents/admin/\nlib/auth.ts  lib/permissions.ts  lib/audit.ts  lib/db.ts  lib/validation.ts\nprisma/schema.prisma  prisma/seed.ts  types/admin.ts')
h(doc,'Request lifecycle',2); tbl(doc,['Step','Implementation rule'],[('Request','Browser requests page or submits form.'),('Authentication','Read server session; reject missing/expired sessions.'),('Authorization','Check role and exact permission for action.'),('Validation','Parse input with shared schema; reject unexpected fields.'),('Transaction','Use Prisma transaction for related updates.'),('Audit','Write immutable record for meaningful mutation/export.'),('Response','Return typed result; revalidate affected route.')])
h(doc,'4 Authentication and authorization'); doc.add_paragraph('The requirements call for secure Owner and Staff login plus one-time verification and password recovery. The supplied screens show username/email login, six-digit verification, forgot password, reset password, and success states. Implement these as a separate auth surface before the protected shell.')
for x in ['Login accepts username or email plus password and records success/failure security events.','Use server-managed, httpOnly, secure, sameSite session cookies; never store admin passwords or session tokens in localStorage.','Store only a strong password hash. Enforce minimum length and rate-limit login, verification, and reset attempts.','Verification codes are single-use, expire after five minutes, and are stored hashed if persisted.','Sign out invalidates the session; sensitive actions may require fresh authentication.']: b(doc,x)
h(doc,'Permission matrix',2); tbl(doc,['Module/action','Owner','Staff'],[('Dashboard and operational reads','Allow','Allow'),('Products, inventory, customers, orders, delivery, returns, feedback, payments','Allow','Allow'),('Marketing and notifications','Allow','Policy-based'),('Reports and exports','Allow','Allow'),('Audit logs','All records','Own activity or limited subset'),('Users and roles','Allow','Deny'),('Backup create/download','Allow','Deny or view-only'),('Restore data','Allow with confirmation','Deny')])
h(doc,'5 Data model blueprint'); doc.add_paragraph('The existing Prisma schema contains only generic user and contacts tables. This is the proposed minimum domain model; confirm final names before migration.')
tbl(doc,['Entity','Important fields','Relationships and notes'],[('admin_user','id, email, username, password_hash, role, status, last_login_at','Owner/Staff; separate from customers.'),('customer','id, name, email, phone, status','Owns addresses, orders, feedback.'),('product','id, sku, name, category_id, price, image_url, reorder_level, status, featured','Catalog and Heritage Showcase.'),('inventory_movement','id, product_id, type, quantity, reason, reference_id, created_by','Stock in/out/adjustment; never erase history.'),('order and order_item','id, customer_id, status, total_amount, fulfillment_method','Constrained status transitions.'),('payment','id, order_id, method, amount, reference, receipt_url, status, verified_by','Verification updates order in transaction.'),('return_request','id, order_id, reason, status, decision_note, decided_by','Approved refund creates reversal.'),('feedback','id, product_id, customer_id, rating, comment, moderation_status','Flagged content hidden from storefront.'),('audit_log','id, actor_id, role, module, action, entity_id, ip_address, metadata, created_at','Append-only.'),('backup_record','id, type, storage_key, size_bytes, status, created_at','Owner restore only.')])
h(doc,'Order and inventory invariants',2)
for x in ['Order flow is Pending -> Processing -> Shipped -> Delivered; Cancelled is terminal.','Payment verification is idempotent; repeated clicks cannot duplicate revenue or stock movement.','Stock cannot become negative unless an explicit, audited emergency override exists.','Every stock change creates a movement record; current quantity is maintained transactionally or derived.']: b(doc,x)
h(doc,'6 Module implementation specification')
mods=[('Login and recovery','/login, /verify, /forgot-password, /reset-password','Secure credentials, six-digit verification, reset expiry, resend cooldown, unauthorized messaging.'),('Dashboard','/dashboard','Today orders, pending orders, monthly revenue, low stock, top products, recent orders, statuses, notifications.'),('Products','/products','Search/filter, add/view/edit/archive/reactivate, images, categories, price, visibility, Heritage Showcase.'),('Inventory','/inventory','Stock, status, reorder level, movements, adjustments, exports, low/out-of-stock alerts.'),('Customers','/customers','Search by name/email/phone; profile, addresses, orders, feedback, suspend/reactivate.'),('Delivery personnel','/delivery-personnel','Accounts, availability, assigned orders, performance; assignments update availability.'),('Orders','/orders','Search, detail, payment, fulfillment, constrained status flow, export.'),('Returns and refunds','/returns-refunds','Review, approve/reject, notes, reversal, customer notification.'),('Feedback','/feedback','Search/filter, flag/unflag, policy-based removal, export.'),('Payments','/payments','Filter, inspect receipt, verify/reject, safely update order, export.'),('Marketing and notifications','/promotions, /notifications','Promotions, validity windows, targeted announcements, sent history.'),('Reports','/reports','Date-filtered sales, orders, delivery, inventory, customers, payments; PDF/CSV.'),('Audit logs','/audit-logs','Read-only searchable logs; Owner all, Staff permitted scope.'),('Backup and restore','/backup-restore','History/settings; Owner trigger/download/restore; failure alert and overwrite warning.')]
for n,path,d in mods: h(doc,n,2); p=doc.add_paragraph(); rr=p.add_run(path+'  '); rr.bold=True; rr.font.color.rgb=RGBColor.from_string(BLUE); p.add_run(d)
h(doc,'7 API and server contract'); doc.add_paragraph('Prefer server actions for simple same-app forms when they fit the deployment model. Use route handlers for integrations, exports, file downloads, and stable HTTP contracts.')
tbl(doc,['Endpoint pattern','Methods','Purpose'],[('/api/admin/products','GET, POST, PATCH','Catalog listing and mutation.'),('/api/admin/orders/[id]','GET, PATCH','Order detail and status transitions.'),('/api/admin/payments/[id]/verify','POST','Idempotent verification, transaction, audit.'),('/api/admin/reports/[type]','GET','Date-filtered data or export.'),('/api/admin/audit-logs','GET','Read-only filtered log query.'),('/api/admin/backups','GET, POST','History and manual trigger.'),('/api/admin/backups/[id]/restore','POST','Owner-only restore with confirmation.')])
code(doc,'type ActionResult<T> =\n  | { ok: true; data: T }\n  | { ok: false; error: { code: string; message: string; field?: string } }\n\nconst session = await requireAdminSession()\nrequirePermission(session, "payments.verify")')
h(doc,'8 Security, privacy, and reliability')
for x in ['Validate every route on the server; client validation is usability only.','Use parameterized Prisma queries; never concatenate user-controlled SQL.','Protect CSRF-sensitive mutations according to the chosen auth/session model.','Redact receipts, passwords, reset tokens, and sensitive metadata from logs.','Use least privilege for database credentials and separate backup storage.','Make large exports asynchronous and enforce date/row limits.','Add error boundaries and loading/empty states; never expose stack traces.']: b(doc,x)
h(doc,'9 Delivery plan'); tbl(doc,['Phase','Deliverables','Exit condition'],[('1 Foundation','Auth/session, shell, permissions, DB client, migrations, seed.','Owner/Staff sign in and reach permitted routes.'),('2 Core operations','Products, inventory, customers, orders, payments.','Test order completes with safe stock/payment changes.'),('3 Extended operations','Delivery, returns, feedback, marketing/notifications.','Edge cases are traceable.'),('4 Intelligence and control','Dashboard, reports, audit, backup/restore.','Owner can monitor, export, audit, recover.'),('5 Hardening','Accessibility, responsive QA, rate limits, tests, deployment.','No critical security/data defects.')])
h(doc,'10 Acceptance checklist')
for x in ['Invalid login is rejected, throttled, and verification expires.','Owner and Staff see correct navigation and cannot directly call unauthorized mutations.','Dashboard reconciles with orders, payments, and inventory.','Product edits validate and appear in catalog/Heritage Showcase.','Every stock change records actor, reason, and timestamp.','Payment verification is idempotent.','Illegal order status jumps are rejected; cancellation is final.','Refund approval creates reversal path and notification event.','Audit logs are immutable in UI and contain useful context.','Exports respect filters, permissions, and hidden fields.','Backup failure alerts Owner; restore requires confirmation and is audited.','Each module has loading, empty, error, responsive, keyboard, and screen-reader states.']: b(doc,x)
h(doc,'Appendix A Source alignment'); doc.add_paragraph('Prepared from the current repository and the supplied AKP web page admin.pdf, WebPageAdminMerged.pdf, Lagarto-AI-and-Grammarian-Reviewed.docx.pdf, and LAGARTO-CHAPTER-4-FINAL.pdf. The references define business context, manual-process problems, functional requirements, and screen concepts. The repository is a Next.js/HeroUI starter with a small Prisma schema, so domain work beyond that baseline is proposed.')
h(doc,'Appendix B Immediate next coding tasks')
for x in ['Expand components/ui/sidebar.tsx into grouped admin navigation with active route matching.','Introduce real admin sessions and the Owner/Staff permission map.','Draft/migrate the domain Prisma schema and seed development data.','Implement Products and Inventory first because they establish catalog and stock invariants.','Add tests for permission gates, order transitions, payment idempotency, and non-negative stock.','Record final decisions for auth provider, file storage, email delivery, and backup target.']: b(doc,x)
doc.save(OUT); print(OUT)
